version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    # とりあえず適当にずっと動いていられるコマンドを仕込んだ状態
    # command: tail -f /dev/null
    # 定期実行するプログラムを永遠に実行
    command: python -u forever_run.py
    environment:
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - python-packages:/root/.local/share
    restart: always
volumes:
  python-packages:
